/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as AuthVerifyEmailRouteImport } from './routes/auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as miscTermsRouteImport } from './routes/(misc)/terms'
import { Route as miscSupportRouteImport } from './routes/(misc)/support'
import { Route as miscPrivacyRouteImport } from './routes/(misc)/privacy'
import { Route as miscPricingRouteImport } from './routes/(misc)/pricing'
import { Route as ProjectsProjectIdRouteRouteImport } from './routes/projects/$projectId/route'
import { Route as ProjectsProjectIdIndexRouteImport } from './routes/projects/$projectId/index'
import { Route as AuthForgetPasswordConfirmRouteImport } from './routes/auth/forget-password.confirm'
import { Route as ProjectsProjectIdBranchesBranchIdRouteImport } from './routes/projects/$projectId/branches/$branchId'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRouteRoute,
} as any)
const miscTermsRoute = miscTermsRouteImport.update({
  id: '/(misc)/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const miscSupportRoute = miscSupportRouteImport.update({
  id: '/(misc)/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const miscPrivacyRoute = miscPrivacyRouteImport.update({
  id: '/(misc)/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const miscPricingRoute = miscPricingRouteImport.update({
  id: '/(misc)/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRouteRoute = ProjectsProjectIdRouteRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdIndexRoute = ProjectsProjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsProjectIdRouteRoute,
} as any)
const AuthForgetPasswordConfirmRoute =
  AuthForgetPasswordConfirmRouteImport.update({
    id: '/forget-password/confirm',
    path: '/forget-password/confirm',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const ProjectsProjectIdBranchesBranchIdRoute =
  ProjectsProjectIdBranchesBranchIdRouteImport.update({
    id: '/branches/$branchId',
    path: '/branches/$branchId',
    getParentRoute: () => ProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/pricing': typeof miscPricingRoute
  '/privacy': typeof miscPrivacyRoute
  '/support': typeof miscSupportRoute
  '/terms': typeof miscTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects/': typeof ProjectsIndexRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/branches/$branchId': typeof ProjectsProjectIdBranchesBranchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/pricing': typeof miscPricingRoute
  '/privacy': typeof miscPrivacyRoute
  '/support': typeof miscSupportRoute
  '/terms': typeof miscTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects': typeof ProjectsIndexRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/projects/$projectId': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/branches/$branchId': typeof ProjectsProjectIdBranchesBranchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/projects/$projectId': typeof ProjectsProjectIdRouteRouteWithChildren
  '/(misc)/pricing': typeof miscPricingRoute
  '/(misc)/privacy': typeof miscPrivacyRoute
  '/(misc)/support': typeof miscSupportRoute
  '/(misc)/terms': typeof miscTermsRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/auth/reset-password': typeof AuthResetPasswordRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verify-email': typeof AuthVerifyEmailRoute
  '/projects/': typeof ProjectsIndexRoute
  '/auth/forget-password/confirm': typeof AuthForgetPasswordConfirmRoute
  '/projects/$projectId/': typeof ProjectsProjectIdIndexRoute
  '/projects/$projectId/branches/$branchId': typeof ProjectsProjectIdBranchesBranchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/projects/$projectId'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/projects/'
    | '/auth/forget-password/confirm'
    | '/projects/$projectId/'
    | '/projects/$projectId/branches/$branchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/pricing'
    | '/privacy'
    | '/support'
    | '/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/projects'
    | '/auth/forget-password/confirm'
    | '/projects/$projectId'
    | '/projects/$projectId/branches/$branchId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/admin'
    | '/projects/$projectId'
    | '/(misc)/pricing'
    | '/(misc)/privacy'
    | '/(misc)/support'
    | '/(misc)/terms'
    | '/auth/forgot-password'
    | '/auth/reset-password'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verify-email'
    | '/projects/'
    | '/auth/forget-password/confirm'
    | '/projects/$projectId/'
    | '/projects/$projectId/branches/$branchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  ProjectsProjectIdRouteRoute: typeof ProjectsProjectIdRouteRouteWithChildren
  miscPricingRoute: typeof miscPricingRoute
  miscPrivacyRoute: typeof miscPrivacyRoute
  miscSupportRoute: typeof miscSupportRoute
  miscTermsRoute: typeof miscTermsRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email': {
      id: '/auth/verify-email'
      path: '/verify-email'
      fullPath: '/auth/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password': {
      id: '/auth/reset-password'
      path: '/reset-password'
      fullPath: '/auth/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(misc)/terms': {
      id: '/(misc)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof miscTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(misc)/support': {
      id: '/(misc)/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof miscSupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(misc)/privacy': {
      id: '/(misc)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof miscPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(misc)/pricing': {
      id: '/(misc)/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof miscPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId/': {
      id: '/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof ProjectsProjectIdIndexRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
    '/auth/forget-password/confirm': {
      id: '/auth/forget-password/confirm'
      path: '/forget-password/confirm'
      fullPath: '/auth/forget-password/confirm'
      preLoaderRoute: typeof AuthForgetPasswordConfirmRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/projects/$projectId/branches/$branchId': {
      id: '/projects/$projectId/branches/$branchId'
      path: '/branches/$branchId'
      fullPath: '/projects/$projectId/branches/$branchId'
      preLoaderRoute: typeof ProjectsProjectIdBranchesBranchIdRouteImport
      parentRoute: typeof ProjectsProjectIdRouteRoute
    }
  }
}

interface AuthRouteRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  AuthForgetPasswordConfirmRoute: typeof AuthForgetPasswordConfirmRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  AuthForgetPasswordConfirmRoute: AuthForgetPasswordConfirmRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface ProjectsProjectIdRouteRouteChildren {
  ProjectsProjectIdIndexRoute: typeof ProjectsProjectIdIndexRoute
  ProjectsProjectIdBranchesBranchIdRoute: typeof ProjectsProjectIdBranchesBranchIdRoute
}

const ProjectsProjectIdRouteRouteChildren: ProjectsProjectIdRouteRouteChildren =
  {
    ProjectsProjectIdIndexRoute: ProjectsProjectIdIndexRoute,
    ProjectsProjectIdBranchesBranchIdRoute:
      ProjectsProjectIdBranchesBranchIdRoute,
  }

const ProjectsProjectIdRouteRouteWithChildren =
  ProjectsProjectIdRouteRoute._addFileChildren(
    ProjectsProjectIdRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  ProjectsProjectIdRouteRoute: ProjectsProjectIdRouteRouteWithChildren,
  miscPricingRoute: miscPricingRoute,
  miscPrivacyRoute: miscPrivacyRoute,
  miscSupportRoute: miscSupportRoute,
  miscTermsRoute: miscTermsRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
