/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createServerRootRoute } from "@tanstack/react-start/server";

import { Route as rootRouteImport } from "./routes/__root";
import { Route as MainAuthedRouteImport } from "./routes/_main/_authed";
import { Route as MainAuthedTodosIdRouteImport } from "./routes/_main/_authed/todos/$id";
import { Route as MainAuthedTodosIndexRouteImport } from "./routes/_main/_authed/todos/index";
import { Route as MainAuthForgotPasswordRouteImport } from "./routes/_main/auth/forgot-password";
import { Route as MainAuthForgotPasswordConfirmRouteImport } from "./routes/_main/auth/forgot-password-confirm";
import { Route as MainAuthResetPasswordRouteImport } from "./routes/_main/auth/reset-password";
import { Route as MainAuthRouteRouteImport } from "./routes/_main/auth/route";
import { Route as MainAuthSignInRouteImport } from "./routes/_main/auth/sign-in";
import { Route as MainAuthSignUpRouteImport } from "./routes/_main/auth/sign-up";
import { Route as MainAuthVerifyEmailRouteImport } from "./routes/_main/auth/verify-email";
import { Route as MainChatRouteImport } from "./routes/_main/chat";
import { Route as MainIndexRouteImport } from "./routes/_main/index";
import { Route as MainRouteRouteImport } from "./routes/_main/route";
import { Route as R3dRouteImport } from "./routes/3d";
import { ServerRoute as ApiSplatServerRouteImport } from "./routes/api.$";
import { ServerRoute as RpcSplatServerRouteImport } from "./routes/rpc.$";

const rootServerRouteImport = createServerRootRoute();

const R3dRoute = R3dRouteImport.update({
  id: "/3d",
  path: "/3d",
  getParentRoute: () => rootRouteImport,
} as any);
const MainRouteRoute = MainRouteRouteImport.update({
  id: "/_main",
  getParentRoute: () => rootRouteImport,
} as any);
const MainIndexRoute = MainIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainChatRoute = MainChatRouteImport.update({
  id: "/chat",
  path: "/chat",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainAuthedRoute = MainAuthedRouteImport.update({
  id: "/_authed",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainAuthRouteRoute = MainAuthRouteRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => MainRouteRoute,
} as any);
const MainAuthVerifyEmailRoute = MainAuthVerifyEmailRouteImport.update({
  id: "/verify-email",
  path: "/verify-email",
  getParentRoute: () => MainAuthRouteRoute,
} as any);
const MainAuthSignUpRoute = MainAuthSignUpRouteImport.update({
  id: "/sign-up",
  path: "/sign-up",
  getParentRoute: () => MainAuthRouteRoute,
} as any);
const MainAuthSignInRoute = MainAuthSignInRouteImport.update({
  id: "/sign-in",
  path: "/sign-in",
  getParentRoute: () => MainAuthRouteRoute,
} as any);
const MainAuthResetPasswordRoute = MainAuthResetPasswordRouteImport.update({
  id: "/reset-password",
  path: "/reset-password",
  getParentRoute: () => MainAuthRouteRoute,
} as any);
const MainAuthForgotPasswordConfirmRoute =
  MainAuthForgotPasswordConfirmRouteImport.update({
    id: "/forgot-password-confirm",
    path: "/forgot-password-confirm",
    getParentRoute: () => MainAuthRouteRoute,
  } as any);
const MainAuthForgotPasswordRoute = MainAuthForgotPasswordRouteImport.update({
  id: "/forgot-password",
  path: "/forgot-password",
  getParentRoute: () => MainAuthRouteRoute,
} as any);
const MainAuthedTodosIndexRoute = MainAuthedTodosIndexRouteImport.update({
  id: "/todos/",
  path: "/todos/",
  getParentRoute: () => MainAuthedRoute,
} as any);
const MainAuthedTodosIdRoute = MainAuthedTodosIdRouteImport.update({
  id: "/todos/$id",
  path: "/todos/$id",
  getParentRoute: () => MainAuthedRoute,
} as any);
const RpcSplatServerRoute = RpcSplatServerRouteImport.update({
  id: "/rpc/$",
  path: "/rpc/$",
  getParentRoute: () => rootServerRouteImport,
} as any);
const ApiSplatServerRoute = ApiSplatServerRouteImport.update({
  id: "/api/$",
  path: "/api/$",
  getParentRoute: () => rootServerRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/3d": typeof R3dRoute;
  "/auth": typeof MainAuthRouteRouteWithChildren;
  "/chat": typeof MainChatRoute;
  "/": typeof MainIndexRoute;
  "/auth/forgot-password": typeof MainAuthForgotPasswordRoute;
  "/auth/forgot-password-confirm": typeof MainAuthForgotPasswordConfirmRoute;
  "/auth/reset-password": typeof MainAuthResetPasswordRoute;
  "/auth/sign-in": typeof MainAuthSignInRoute;
  "/auth/sign-up": typeof MainAuthSignUpRoute;
  "/auth/verify-email": typeof MainAuthVerifyEmailRoute;
  "/todos/$id": typeof MainAuthedTodosIdRoute;
  "/todos": typeof MainAuthedTodosIndexRoute;
}
export interface FileRoutesByTo {
  "/3d": typeof R3dRoute;
  "/auth": typeof MainAuthRouteRouteWithChildren;
  "/chat": typeof MainChatRoute;
  "/": typeof MainIndexRoute;
  "/auth/forgot-password": typeof MainAuthForgotPasswordRoute;
  "/auth/forgot-password-confirm": typeof MainAuthForgotPasswordConfirmRoute;
  "/auth/reset-password": typeof MainAuthResetPasswordRoute;
  "/auth/sign-in": typeof MainAuthSignInRoute;
  "/auth/sign-up": typeof MainAuthSignUpRoute;
  "/auth/verify-email": typeof MainAuthVerifyEmailRoute;
  "/todos/$id": typeof MainAuthedTodosIdRoute;
  "/todos": typeof MainAuthedTodosIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/_main": typeof MainRouteRouteWithChildren;
  "/3d": typeof R3dRoute;
  "/_main/auth": typeof MainAuthRouteRouteWithChildren;
  "/_main/_authed": typeof MainAuthedRouteWithChildren;
  "/_main/chat": typeof MainChatRoute;
  "/_main/": typeof MainIndexRoute;
  "/_main/auth/forgot-password": typeof MainAuthForgotPasswordRoute;
  "/_main/auth/forgot-password-confirm": typeof MainAuthForgotPasswordConfirmRoute;
  "/_main/auth/reset-password": typeof MainAuthResetPasswordRoute;
  "/_main/auth/sign-in": typeof MainAuthSignInRoute;
  "/_main/auth/sign-up": typeof MainAuthSignUpRoute;
  "/_main/auth/verify-email": typeof MainAuthVerifyEmailRoute;
  "/_main/_authed/todos/$id": typeof MainAuthedTodosIdRoute;
  "/_main/_authed/todos/": typeof MainAuthedTodosIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/3d"
    | "/auth"
    | "/chat"
    | "/"
    | "/auth/forgot-password"
    | "/auth/forgot-password-confirm"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/todos/$id"
    | "/todos";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/3d"
    | "/auth"
    | "/chat"
    | "/"
    | "/auth/forgot-password"
    | "/auth/forgot-password-confirm"
    | "/auth/reset-password"
    | "/auth/sign-in"
    | "/auth/sign-up"
    | "/auth/verify-email"
    | "/todos/$id"
    | "/todos";
  id:
    | "__root__"
    | "/_main"
    | "/3d"
    | "/_main/auth"
    | "/_main/_authed"
    | "/_main/chat"
    | "/_main/"
    | "/_main/auth/forgot-password"
    | "/_main/auth/forgot-password-confirm"
    | "/_main/auth/reset-password"
    | "/_main/auth/sign-in"
    | "/_main/auth/sign-up"
    | "/_main/auth/verify-email"
    | "/_main/_authed/todos/$id"
    | "/_main/_authed/todos/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  MainRouteRoute: typeof MainRouteRouteWithChildren;
  R3dRoute: typeof R3dRoute;
}
export interface FileServerRoutesByFullPath {
  "/api/$": typeof ApiSplatServerRoute;
  "/rpc/$": typeof RpcSplatServerRoute;
}
export interface FileServerRoutesByTo {
  "/api/$": typeof ApiSplatServerRoute;
  "/rpc/$": typeof RpcSplatServerRoute;
}
export interface FileServerRoutesById {
  __root__: typeof rootServerRouteImport;
  "/api/$": typeof ApiSplatServerRoute;
  "/rpc/$": typeof RpcSplatServerRoute;
}
export interface FileServerRouteTypes {
  fileServerRoutesByFullPath: FileServerRoutesByFullPath;
  fullPaths: "/api/$" | "/rpc/$";
  fileServerRoutesByTo: FileServerRoutesByTo;
  to: "/api/$" | "/rpc/$";
  id: "__root__" | "/api/$" | "/rpc/$";
  fileServerRoutesById: FileServerRoutesById;
}
export interface RootServerRouteChildren {
  ApiSplatServerRoute: typeof ApiSplatServerRoute;
  RpcSplatServerRoute: typeof RpcSplatServerRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/3d": {
      id: "/3d";
      path: "/3d";
      fullPath: "/3d";
      preLoaderRoute: typeof R3dRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main": {
      id: "/_main";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainRouteRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/_main/": {
      id: "/_main/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof MainIndexRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/chat": {
      id: "/_main/chat";
      path: "/chat";
      fullPath: "/chat";
      preLoaderRoute: typeof MainChatRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/_authed": {
      id: "/_main/_authed";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof MainAuthedRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/auth": {
      id: "/_main/auth";
      path: "/auth";
      fullPath: "/auth";
      preLoaderRoute: typeof MainAuthRouteRouteImport;
      parentRoute: typeof MainRouteRoute;
    };
    "/_main/auth/verify-email": {
      id: "/_main/auth/verify-email";
      path: "/verify-email";
      fullPath: "/auth/verify-email";
      preLoaderRoute: typeof MainAuthVerifyEmailRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/auth/sign-up": {
      id: "/_main/auth/sign-up";
      path: "/sign-up";
      fullPath: "/auth/sign-up";
      preLoaderRoute: typeof MainAuthSignUpRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/auth/sign-in": {
      id: "/_main/auth/sign-in";
      path: "/sign-in";
      fullPath: "/auth/sign-in";
      preLoaderRoute: typeof MainAuthSignInRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/auth/reset-password": {
      id: "/_main/auth/reset-password";
      path: "/reset-password";
      fullPath: "/auth/reset-password";
      preLoaderRoute: typeof MainAuthResetPasswordRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/auth/forgot-password-confirm": {
      id: "/_main/auth/forgot-password-confirm";
      path: "/forgot-password-confirm";
      fullPath: "/auth/forgot-password-confirm";
      preLoaderRoute: typeof MainAuthForgotPasswordConfirmRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/auth/forgot-password": {
      id: "/_main/auth/forgot-password";
      path: "/forgot-password";
      fullPath: "/auth/forgot-password";
      preLoaderRoute: typeof MainAuthForgotPasswordRouteImport;
      parentRoute: typeof MainAuthRouteRoute;
    };
    "/_main/_authed/todos/": {
      id: "/_main/_authed/todos/";
      path: "/todos";
      fullPath: "/todos";
      preLoaderRoute: typeof MainAuthedTodosIndexRouteImport;
      parentRoute: typeof MainAuthedRoute;
    };
    "/_main/_authed/todos/$id": {
      id: "/_main/_authed/todos/$id";
      path: "/todos/$id";
      fullPath: "/todos/$id";
      preLoaderRoute: typeof MainAuthedTodosIdRouteImport;
      parentRoute: typeof MainAuthedRoute;
    };
  }
}
declare module "@tanstack/react-start/server" {
  interface ServerFileRoutesByPath {
    "/rpc/$": {
      id: "/rpc/$";
      path: "/rpc/$";
      fullPath: "/rpc/$";
      preLoaderRoute: typeof RpcSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
    "/api/$": {
      id: "/api/$";
      path: "/api/$";
      fullPath: "/api/$";
      preLoaderRoute: typeof ApiSplatServerRouteImport;
      parentRoute: typeof rootServerRouteImport;
    };
  }
}

interface MainAuthRouteRouteChildren {
  MainAuthForgotPasswordRoute: typeof MainAuthForgotPasswordRoute;
  MainAuthForgotPasswordConfirmRoute: typeof MainAuthForgotPasswordConfirmRoute;
  MainAuthResetPasswordRoute: typeof MainAuthResetPasswordRoute;
  MainAuthSignInRoute: typeof MainAuthSignInRoute;
  MainAuthSignUpRoute: typeof MainAuthSignUpRoute;
  MainAuthVerifyEmailRoute: typeof MainAuthVerifyEmailRoute;
}

const MainAuthRouteRouteChildren: MainAuthRouteRouteChildren = {
  MainAuthForgotPasswordRoute: MainAuthForgotPasswordRoute,
  MainAuthForgotPasswordConfirmRoute: MainAuthForgotPasswordConfirmRoute,
  MainAuthResetPasswordRoute: MainAuthResetPasswordRoute,
  MainAuthSignInRoute: MainAuthSignInRoute,
  MainAuthSignUpRoute: MainAuthSignUpRoute,
  MainAuthVerifyEmailRoute: MainAuthVerifyEmailRoute,
};

const MainAuthRouteRouteWithChildren = MainAuthRouteRoute._addFileChildren(
  MainAuthRouteRouteChildren,
);

interface MainAuthedRouteChildren {
  MainAuthedTodosIdRoute: typeof MainAuthedTodosIdRoute;
  MainAuthedTodosIndexRoute: typeof MainAuthedTodosIndexRoute;
}

const MainAuthedRouteChildren: MainAuthedRouteChildren = {
  MainAuthedTodosIdRoute: MainAuthedTodosIdRoute,
  MainAuthedTodosIndexRoute: MainAuthedTodosIndexRoute,
};

const MainAuthedRouteWithChildren = MainAuthedRoute._addFileChildren(
  MainAuthedRouteChildren,
);

interface MainRouteRouteChildren {
  MainAuthRouteRoute: typeof MainAuthRouteRouteWithChildren;
  MainAuthedRoute: typeof MainAuthedRouteWithChildren;
  MainChatRoute: typeof MainChatRoute;
  MainIndexRoute: typeof MainIndexRoute;
}

const MainRouteRouteChildren: MainRouteRouteChildren = {
  MainAuthRouteRoute: MainAuthRouteRouteWithChildren,
  MainAuthedRoute: MainAuthedRouteWithChildren,
  MainChatRoute: MainChatRoute,
  MainIndexRoute: MainIndexRoute,
};

const MainRouteRouteWithChildren = MainRouteRoute._addFileChildren(
  MainRouteRouteChildren,
);

const rootRouteChildren: RootRouteChildren = {
  MainRouteRoute: MainRouteRouteWithChildren,
  R3dRoute: R3dRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
const rootServerRouteChildren: RootServerRouteChildren = {
  ApiSplatServerRoute: ApiSplatServerRoute,
  RpcSplatServerRoute: RpcSplatServerRoute,
};
export const serverRouteTree = rootServerRouteImport
  ._addFileChildren(rootServerRouteChildren)
  ._addFileTypes<FileServerRouteTypes>();
